### Korak A: Pokretanje novog TCP skeniranja (POST)
POST https://localhost:7049/api/scan/tcp
Content-Type: application/json

{
  "host": "127.0.0.1",
  "startPort": 78,
  "endPort": 82
}

### Korak B: Provera statusa posla (GET)
GET https://localhost:7049/api/scan/787cbaf7-4f96-4598-bfb4-bccf53b955b2/status
Accept: application/json
